### ISSUE TITLE
Symbol's value as variable is void: pdf-filename

### ISSUE THREAD

**Issue by atanasj** [dalanicolai/doc-tools-toc#1]
Hi,

Thanks for a package that will make working with PDFs that little bit easier. However, I am having a problem when trying to use the `doc-toc--pdftocgen-add-to-pdf` function, and getting the error message: `Symbol's value as variable is void: pdf-filename`.

The `toc` gets added the PDF as expected, but what is the error about?

I am using `doomemacs` and `MacOS` with `Emacs 28.2`.

Please let me know if need more info.

**Comment by dalanicolai** [comment]
Thanks for reporting this issue. However, the package its ELPA page includes [usage instructions](https://elpa.gnu.org/packages/doc-toc.html#org5241940), and you should not be using the mentioned function directly. I am unable to reproduce the behavior when following the instructions.

**Comment by atanasj** [comment]
Figured this out finally. Was a dependency and config issue on my end. Thanks!
